name: CI
on:
  pull_request:
  push:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Cargo version
        id: cargo_version
        run: echo "::set-output name=version::$(cargo -V | tr -d ' ')"
        shell: bash

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.cargo_version.outputs.version }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-${{ steps.cargo_version.outputs.version }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --features=serde --verbose
