name: CI
on:
  pull_request:
  push:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --features=serde --verbose
